memory_limit = -1
; Tempo máximo para uma requisição ser processada (0 = desativado)
request_terminate_timeout = 300s

; Tempo máximo de execução de um script (já ajustado no seu código)
max_execution_time = 120