version: '2'
services:
  database_dev:
    image: mariadb:10
    container_name: database_dev
    volumes:
      # - database_dev:/var/lib/mysql
      - ./files:/opt/files
    ports:
      - 4236:3306
    environment:
      - MYSQL_DATABASE=seara
      - MYSQL_ROOT_PASSWORD=root
  php:
    image: fcoedno/php:7.1-fpm-dev
    container_name: php_dev
    volumes:
      - ./:/code
      - composercache:/.composer
      - './docker/php/docker-php-composer.ini:/usr/local/etc/php/conf.d/docker-php-composer.ini'
    working_dir: /code
  web_dev:
    image: fcoedno/nginx:1.13.8-dev
    container_name: web_dev
    volumes:
      - ./:/code:ro
    depends_on:
      - php
    ports:
      - 8000:80
    environment:
      - NGINX_HOST=seara.localhost
      - NGINX_ROOT=/code/public
  node_dev:
    container_name: node_dev
    build: docker/node/
    volumes:
      - ./:/code
    working_dir: /code
    command: tail -f /dev/null
volumes:
  database_dev:
  composercache:

