version: '2'
services:
  database:
    image: mariadb:10
    volumes:
      - database:/var/lib/mysql
    ports:
      - 4242:3306
    environment:
      - MYSQL_DATABASE=vetdb
      - MYSQL_ROOT_PASSWORD=root
  php:
    image: fcoedno/php:7.1-fpm-dev
    #build: docker/
    volumes:
      - ./:/var/www/app
      - composercache:/.composer
    working_dir: /var/www/app
    environment:
      - USER_ID=${UID}
      - APP_ENV=dev
    user: ${UID}
  web:
    image: fcoedno/nginx:1.13.8-dev
    volumes:
      - ./:/var/www/app:ro
    depends_on:
      - php
    ports:
      - 80:80
    environment:
      - NGINX_HOST=seara.localhost
  node:
    build: docker/node/
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    user: ${UID}
volumes:
  database:
  composercache:

